import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { flattenTokens, readJson, resolveAlias, type FlatTokens } from './lib.js';

const here = dirname(fileURLToPath(import.meta.url));
const tokensDir = resolve(here, 'tokens');
const repoRoot = resolve(here, '../../..');
const generatedCssPath = resolve(repoRoot, 'apps/game/src/app/tokens.generated.css');
const resolvedJsonPath = resolve(here, '../tokens.resolved.json');
const generatedTsPath = resolve(here, 'generated/tokens.ts');

const primitives = flattenTokens(readJson(resolve(tokensDir, 'primitives.json')));
const dimensions = flattenTokens(readJson(resolve(tokensDir, 'dimensions.json')));
const typography = flattenTokens(readJson(resolve(tokensDir, 'typography.json')));

function resolveSemantic(file: string): Record<string, string> {
  const raw = flattenTokens(readJson(resolve(tokensDir, file)));
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(raw)) {
    out[key.replace(/^color\./, '')] = String(resolveAlias(value, primitives));
  }
  return out;
}

const light = resolveSemantic('semantic.light.json');
const night = resolveSemantic('semantic.night.json');

function pick(flat: FlatTokens, prefix: string): [string, string | number][] {
  return Object.entries(flat)
    .filter(([key]) => key.startsWith(prefix))
    .map(([key, value]) => [key.slice(prefix.length), value]);
}

const theme: string[] = [`  --font-sans: ${typography['font.family.sans']};`];
for (const [name, value] of pick(typography, 'font.weight.')) {
  theme.push(`  --font-weight-${name}: ${value};`);
}
for (const [name, value] of pick(typography, 'font.size.')) {
  theme.push(`  --text-${name}: ${value};`);
}
for (const [name, value] of pick(typography, 'font.lineHeight.')) {
  theme.push(`  --leading-${name}: ${value};`);
}
for (const [name, value] of pick(dimensions, 'spacing.')) {
  theme.push(`  --spacing-${name}: ${value};`);
}
for (const [name, value] of pick(dimensions, 'radius.')) {
  theme.push(`  --radius-${name}: ${value};`);
}
for (const [name, value] of Object.entries(light)) {
  theme.push(`  --color-${name}: ${value};`);
}

const nightOverrides: string[] = ['  color-scheme: dark;'];
for (const [name, value] of Object.entries(night)) {
  if (value !== light[name]) {
    nightOverrides.push(`  --color-${name}: ${value};`);
  }
}

const css = [
  '/* AUTO-GENERATED by packages/tokens/src/build.ts - do not edit by hand. */',
  '/* Source of truth: packages/tokens/src/tokens/*.json (run `pnpm tokens:build`). */',
  '',
  '@theme {',
  ...theme,
  '}',
  '',
  "[data-theme='night'] {",
  ...nightOverrides,
  '}',
  ''
].join('\n');
writeFileSync(generatedCssPath, css);

const resolved = { primitives, semantic: { light, night }, dimensions, typography };
writeFileSync(resolvedJsonPath, `${JSON.stringify(resolved, null, 2)}\n`);

mkdirSync(dirname(generatedTsPath), { recursive: true });
const generated = `// AUTO-GENERATED by packages/tokens/src/build.ts - do not edit by hand.
export const primitiveTokens = ${JSON.stringify(primitives, null, 2)} as const;
export const lightTokens = ${JSON.stringify(light, null, 2)} as const;
export const nightTokens = ${JSON.stringify(night, null, 2)} as const;
export const dimensionTokens = ${JSON.stringify(dimensions, null, 2)} as const;
export const typographyTokens = ${JSON.stringify(typography, null, 2)} as const;
export type SemanticColorName = keyof typeof lightTokens;
`;
writeFileSync(generatedTsPath, generated);

console.log(
  `[tokens] generated ${Object.keys(light).length} colors, ` +
    `${pick(dimensions, 'spacing.').length} spacing, ${pick(dimensions, 'radius.').length} radii, ` +
    `${pick(typography, 'font.size.').length} type sizes`
);
