import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { emaux, engine, schools, skins, toBase, type SkinId } from './kw-system.js';

// Génère le CSS multi-skin (moteur + pack Terres Oubliées) consommé par apps/game,
// à partir de la source unique kw-system.ts. Modes : Jour (défaut) + Veillée (nuit).

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../..');
const generatedCssPath = resolve(repoRoot, 'apps/game/src/app/tokens.generated.css');
const resolvedJsonPath = resolve(here, '../tokens.resolved.json');

const DEFAULT_SKIN: SkinId = 'grimoire';

const colorVars = (map: object): string[] =>
  Object.entries(map).map(([role, hex]) => `  --color-${role}: ${String(hex)};`);

const fontVars = (fonts: { display: string; body: string; label: string }): string[] => [
  `  --font-display: ${fonts.display};`,
  `  --font-body: ${fonts.body};`,
  `  --font-label: ${fonts.label};`
];

const def = skins[DEFAULT_SKIN];

// @theme : seulement ce qui doit générer des utilitaires Tailwind (couleurs, tailles, polices, radius, leading)
const theme: string[] = [
  `  --radius-rect: ${engine.geometry.radiusRect};`,
  `  --radius-disc: ${engine.geometry.radiusDisc};`,
  `  --leading-tight: ${engine.type.lineHeight.tight};`,
  `  --leading-normal: ${engine.type.lineHeight.normal};`
];
for (const [name, value] of Object.entries(engine.type.size)) {
  theme.push(`  --text-${name}: ${value};`);
}
theme.push(...colorVars(def.jour));
theme.push(...colorVars(toBase.jourFeedback));
theme.push(...fontVars(def.fonts));
theme.push(`  --font-mono: ${toBase.fonts.mono};`);

// :root brut : tokens consommés via var() (géométrie, ombres, tracking, écoles).
// Hors @theme pour éviter le tree-shaking Tailwind v4 des vars non utilisées par un utilitaire.
const rootEngine: string[] = [
  `  --border-hairline: ${engine.geometry.borderHairline};`,
  `  --border-strong: ${engine.geometry.borderStrong};`,
  `  --shadow-card: ${engine.geometry.shadowCard};`,
  `  --shadow-button: ${engine.geometry.shadowButton};`,
  `  --tracking-label: ${engine.type.label.tracking};`
];
for (const [name, school] of Object.entries(schools)) {
  rootEngine.push(`  --school-${name}: ${school.color};`);
}
for (const [name, e] of Object.entries(emaux)) {
  rootEngine.push(`  --emaux-${name}: ${e.color};`);
}

// Skins par surface (Jour) + leur override Veillée (accent, + canvas du Tripot)
const skinBlocks: string[] = [];
const nightSkinBlocks: string[] = [];
for (const [id, skin] of Object.entries(skins)) {
  skinBlocks.push(
    `[data-skin='${id}'] {\n${colorVars(skin.jour).join('\n')}\n${fontVars(skin.fonts).join('\n')}\n}`
  );
  const night: string[] = [];
  if ('veilleeCanvas' in skin && skin.veilleeCanvas) {
    night.push(`  --color-bg-canvas: ${skin.veilleeCanvas};`);
  }
  if ('veillee' in skin && skin.veillee) {
    night.push(...colorVars(skin.veillee)); // rampe nuit propre au pack
  }
  night.push(...colorVars(skin.veilleeAccent));
  nightSkinBlocks.push(`[data-skin='${id}'][data-theme='night'] {\n${night.join('\n')}\n}`);
}

// Veillée partagée : rampe sombre commune + feedback nuit + accent du skin par défaut
const nightShared = `[data-theme='night'] {\n  color-scheme: dark;\n${colorVars(
  toBase.veillee
).join('\n')}\n${colorVars(def.veilleeAccent).join('\n')}\n}`;

const css = [
  '/* AUTO-GENERATED by packages/tokens/src/build.ts - do not edit by hand. */',
  '/* Source: packages/tokens/src/kw-system.ts (run `pnpm tokens:build`). */',
  '',
  '@theme {',
  ...theme,
  '}',
  '',
  '/* --- Tokens moteur via var() (hors @theme, toujours emis) --- */',
  ':root {',
  ...rootEngine,
  '}',
  '',
  '/* --- Skins par surface (Jour) --- */',
  ...skinBlocks,
  '',
  '/* --- Veillee (nuit) : rampe partagee + accent par skin --- */',
  nightShared,
  ...nightSkinBlocks,
  ''
].join('\n');
writeFileSync(generatedCssPath, css);

writeFileSync(
  resolvedJsonPath,
  `${JSON.stringify({ engine, toBase, skins, schools, defaultSkin: DEFAULT_SKIN }, null, 2)}\n`
);

console.log(
  `[kw-tokens] ${Object.keys(skins).length} skins, ${Object.keys(schools).length} ecoles, default=${DEFAULT_SKIN}`
);
