/**
 * E0.4 — Construit `data/catalogs/armes-paper.yaml` depuis la table du fichier Armes paper.
 *
 * Source = table tab-séparée : `Arme · TD · Dégât · Difficulté · Spécial · Poids`. Sortant un
 * `catalog_yaml`, chaque arme devient une unité canonique/NOMOS atomisée. Réconciliation avec
 * `armes.yaml` (web) = E0.4b. Voir docs/plan/PROSE-SOURCE-LINKAGE.md.
 *
 * Usage : `pnpm catalogs:build:armes-paper`
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { dump } from 'js-yaml';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_REL = 'data/legacy/paper/regles-papier/extracted/listes/armes.md';
const OUTPUT_REL = 'data/catalogs/armes-paper.yaml';

interface Weapon {
  id: string;
  name: string;
  damage_type?: string;
  damage?: string;
  difficulty?: string;
  special?: string;
  weight_kg?: number;
  source_refs: Array<{ path: string; sha256: string; ref: string }>;
}

function slugify(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function cell(cells: string[], index: number): string | undefined {
  const value = (cells[index] ?? '').trim();
  return value.length > 0 ? value : undefined;
}

function main(): void {
  const content = readFileSync(join(ROOT, SOURCE_REL), 'utf8');
  const hash = createHash('sha256').update(content).digest('hex');
  const lines = content.split('\n').map((l) => l.replace(/\r$/, ''));

  const headerIndex = lines.findIndex((l) => /^Arme\t.*Dégât/i.test(l));
  if (headerIndex === -1) throw new Error('armes header row not found');

  const weapons: Weapon[] = [];
  const seen = new Map<string, number>();
  for (let i = headerIndex + 1; i < lines.length; i += 1) {
    const line = lines[i];
    if (!line.includes('\t')) continue; // table rows are tab-delimited
    if (line.trim() === '' || line.trim() === '```') continue;
    const cells = line.split('\t');
    const name = (cells[0] ?? '').trim();
    if (name.length === 0) continue;
    const weight = cell(cells, 5);
    const parsedWeight = weight ? Number.parseFloat(weight.replace(',', '.')) : NaN;
    let id = slugify(name);
    const count = seen.get(id) ?? 0;
    seen.set(id, count + 1);
    if (count > 0) id = `${id}-${count + 1}`;
    weapons.push({
      id,
      name,
      damage_type: cell(cells, 1),
      damage: cell(cells, 2),
      difficulty: cell(cells, 3),
      special: cell(cells, 4),
      ...(Number.isFinite(parsedWeight) ? { weight_kg: parsedWeight } : {}),
      source_refs: [{ path: SOURCE_REL, sha256: hash, ref: `entry:${id}` }]
    });
  }

  const catalog = {
    version: 1,
    metadata: {
      source: SOURCE_REL,
      source_sha256: hash,
      imported_at: '2026-05-27',
      total_entries: weapons.length,
      catalog_status: 'partial',
      notes:
        'Armes du document paper : type de degat (TD = P/E/C/T), formule de degat, difficulte, ' +
        'special, poids (kg). Reconciliation avec armes.yaml (web) = E0.4b.'
    },
    weapons
  };

  const yaml = `# Generated by \`pnpm catalogs:build:armes-paper\`. Do not edit by hand.\n${dump(
    catalog,
    { lineWidth: 120, noRefs: true }
  )}`;
  writeFileSync(join(ROOT, OUTPUT_REL), yaml, 'utf8');
  console.log(`armes-paper catalog written: ${weapons.length} armes`);
  const withType = weapons.filter((w) => w.damage_type !== undefined).length;
  const withWeight = weapons.filter((w) => w.weight_kg !== undefined).length;
  console.log(`  avec TD: ${withType} ; avec poids: ${withWeight}`);
}

main();
