import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import yaml from 'js-yaml';

const ROOT = join(import.meta.dirname ?? __dirname, '..');
const BESTIAIRE_PATH = join(ROOT, 'data/catalogs/bestiaire.yaml');
const OUTPUT_PATH = join(ROOT, 'data/catalogs/races.yaml');
const RELATIVE_BESTIAIRE = 'data/catalogs/bestiaire.yaml';

interface SourceRef {
  path: string;
  sha256: string;
  ref: string;
}

interface BestiaryCreature {
  id: string;
  name: string;
  status: 'active' | 'ambiguous' | 'deprecated' | 'raw_reference_only';
  category: string;
  size_m: number;
  life_expectancy: number;
  xp_category: number;
  vitality_base: number;
  speed_factor_base: number;
  will_factor_base: number;
  attribute_max: Record<string, number>;
  innate_atouts?: string[];
  innate_handicaps?: string[];
  resistances?: Array<Record<string, unknown>>;
  intelligence_level?: string;
  language_capable: boolean;
  habitat?: string[];
  social_structure?: string;
  playable: boolean;
  lore?: string;
  source_refs: SourceRef[];
  metadata?: Record<string, unknown>;
}

interface BestiaryCatalog {
  version: number;
  metadata?: {
    imported_at?: string;
    source_files?: SourceRef[];
    updated_at?: string;
  } & Record<string, unknown>;
  creatures: BestiaryCreature[];
}

interface RaceEntry {
  id: string;
  name: string;
  status: BestiaryCreature['status'];
  playable: boolean;
  taxonomy: string;
  xp_category: number;
  vitality_base: number;
  speed_factor_base: number;
  will_factor_base: number;
  attribute_max: Record<string, number>;
  innate_atouts: string[];
  innate_handicaps: string[];
  resistances: Array<Record<string, unknown>>;
  size_m: number;
  life_expectancy: number;
  intelligence_level?: string;
  language_capable: boolean;
  habitat: string[];
  social_structure?: string;
  lore?: string;
  source_refs: SourceRef[];
  metadata?: Record<string, unknown>;
}

function main(): void {
  const content = readFileSync(BESTIAIRE_PATH, 'utf8');
  const sourceHash = createHash('sha256').update(content).digest('hex');
  const bestiary = yaml.load(content) as BestiaryCatalog;
  const races = bestiary.creatures.map(toRaceEntry);

  const payload = {
    version: 1,
    metadata: {
      source: RELATIVE_BESTIAIRE,
      source_sha256: sourceHash,
      imported_at: bestiary.metadata?.updated_at ?? bestiary.metadata?.imported_at,
      total_entries: races.length,
      total_playable_races: races.filter((race) => race.playable).length,
      source_files: bestiary.metadata?.source_files ?? [],
      notes:
        'Catalogue races extrait du bestiaire canonique web/paper. Inclut les 31 races nommées du domaine D3 avec drapeau playable pour distinguer les races disponibles au wizard PJ. docs/rules/03-races.md annonce 33 races, mais deux noms ne sont pas identifiés dans les sources structurées ; voir data/catalogs/races-ambiguites.md.'
    },
    races
  };

  const output = yaml.dump(payload, {
    lineWidth: 120,
    noRefs: true,
    quotingType: '"',
    forceQuotes: false
  });
  const banner = '# Generated by `pnpm catalogs:build:races`. Do not edit by hand.\n';
  writeFileSync(OUTPUT_PATH, banner + output, 'utf8');

  execFileSync('pnpm', ['exec', 'prettier', '--write', OUTPUT_PATH], {
    cwd: ROOT,
    stdio: 'inherit'
  });
  console.log(`Wrote ${OUTPUT_PATH} (${races.length} races)`);
}

function toRaceEntry(creature: BestiaryCreature): RaceEntry {
  return {
    id: creature.id,
    name: creature.name,
    status: creature.status,
    playable: creature.playable,
    taxonomy: creature.category,
    xp_category: creature.xp_category,
    vitality_base: creature.vitality_base,
    speed_factor_base: creature.speed_factor_base,
    will_factor_base: creature.will_factor_base,
    attribute_max: creature.attribute_max,
    innate_atouts: creature.innate_atouts ?? [],
    innate_handicaps: creature.innate_handicaps ?? [],
    resistances: creature.resistances ?? [],
    size_m: creature.size_m,
    life_expectancy: creature.life_expectancy,
    intelligence_level: creature.intelligence_level,
    language_capable: creature.language_capable,
    habitat: creature.habitat ?? [],
    social_structure: creature.social_structure,
    lore: creature.lore,
    source_refs: creature.source_refs,
    metadata: creature.metadata
  };
}

main();
