import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import yaml from 'js-yaml';

const ROOT = join(import.meta.dirname ?? __dirname, '..');
const SOURCE_PATH = join(ROOT, 'data/legacy/web-scraped/documents/atouts/index.md');
const RELATIVE_SOURCE = 'data/legacy/web-scraped/documents/atouts/index.md';
const OUTPUT_PATH = join(ROOT, 'data/catalogs/atouts.yaml');

const TYPE_VALUES = new Set(['Classe', 'Neutre', 'Orientation']);
const ACTIVATION_VALUES = new Set(['Permanent', 'Ephémère']);

interface AtoutEntry {
  id: string;
  name: string;
  effect: string;
  value: number;
  activation: 'permanent' | 'ephemere';
  scope: 'classe' | 'neutre' | 'orientation';
  source_refs: Array<{ path: string; sha256: string; ref: string }>;
}

function slugify(value: string): string {
  return value
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function parseValue(token: string): number | null {
  const cleaned = token.replace(/[^\d-]/g, '');
  if (!cleaned) return null;
  const parsed = Number.parseInt(cleaned, 10);
  return Number.isNaN(parsed) ? null : parsed;
}

function parse(): { atouts: AtoutEntry[]; sourceHash: string } {
  const content = readFileSync(SOURCE_PATH, 'utf8');
  const sourceHash = createHash('sha256').update(content).digest('hex');
  const lines = content.split('\n').map((line) => line.trim());

  const headerIdx = lines.findIndex((line) => line === 'Type');
  if (headerIdx === -1) throw new Error('Header "Type" not found');

  const atouts: AtoutEntry[] = [];
  const idCounter = new Map<string, number>();
  let blockStart = headerIdx + 1;

  for (let i = blockStart; i < lines.length; i += 1) {
    const line = lines[i];
    if (!TYPE_VALUES.has(line)) continue;

    const typeLine = line;
    const activationLine = lines[i - 1];
    const valueLine = lines[i - 2];

    if (!ACTIVATION_VALUES.has(activationLine)) {
      blockStart = i + 1;
      continue;
    }
    const value = parseValue(valueLine);
    if (value === null) {
      blockStart = i + 1;
      continue;
    }

    const blockEnd = i - 3;
    const blockLines = lines.slice(blockStart, blockEnd + 1).filter((l) => l.length > 0);
    if (blockLines.length === 0) {
      blockStart = i + 1;
      continue;
    }

    const name = blockLines[0];
    const effect = blockLines.slice(1).join(' ').trim();

    let id = slugify(name);
    const occ = idCounter.get(id) ?? 0;
    idCounter.set(id, occ + 1);
    if (occ > 0) id = `${id}-${slugify(typeLine)}-${occ}`;

    atouts.push({
      id,
      name,
      effect,
      value,
      activation: activationLine === 'Permanent' ? 'permanent' : 'ephemere',
      scope: typeLine.toLowerCase() as AtoutEntry['scope'],
      source_refs: [{ path: RELATIVE_SOURCE, sha256: sourceHash, ref: `entry:${id}` }]
    });

    blockStart = i + 1;
  }

  return { atouts, sourceHash };
}

function main(): void {
  const { atouts, sourceHash } = parse();
  const today = new Date().toISOString().slice(0, 10);

  const payload = {
    version: 1,
    metadata: {
      source: RELATIVE_SOURCE,
      source_sha256: sourceHash,
      imported_at: today,
      total_entries: atouts.length,
      catalog_status: 'partial',
      notes:
        'Atouts/handicaps extraits de la liste web canonique (assets-list). Scope: classe / neutre / orientation. Activation: permanent / ephemere. Les valeurs négatives (handicaps) sont conservées telles quelles. Les niveau-atouts sont dans atouts-niveaux web (à instruire séparément).'
    },
    atouts
  };

  const yamlOutput = yaml.dump(payload, {
    lineWidth: 120,
    noRefs: true,
    quotingType: '"',
    forceQuotes: false
  });
  const banner = '# Generated by `pnpm catalogs:build:atouts`. Do not edit by hand.\n';
  writeFileSync(OUTPUT_PATH, banner + yamlOutput, 'utf8');

  execFileSync('pnpm', ['exec', 'prettier', '--write', OUTPUT_PATH], {
    cwd: ROOT,
    stdio: 'inherit'
  });
  console.log(`Wrote ${OUTPUT_PATH} (${atouts.length} atouts)`);
}

main();
