/**
 * E0.4 — Construit `data/catalogs/protections-paper.yaml` depuis le document Protections paper.
 *
 * Structure 2 niveaux : header `P E C T Poids` → ligne **matériau** (nom + 4 valeurs d'armure
 * P/E/C/T) → lignes **pièces** (nom + poids kg). Sortant un `catalog_yaml`, chaque matériau devient
 * une unité atomisée. Réconciliation avec `protections.yaml` (web) = E0.4b.
 *
 * Usage : `pnpm catalogs:build:protections-paper`
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { dump } from 'js-yaml';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_REL = 'data/legacy/paper/regles-papier/extracted/listes/protections.md';
const OUTPUT_REL = 'data/catalogs/protections-paper.yaml';

interface Piece {
  name: string;
  weight_kg?: number;
}
interface Material {
  id: string;
  name: string;
  armor: { p: number; e: number; c: number; t: number };
  pieces: Piece[];
  source_refs: Array<{ path: string; sha256: string; ref: string }>;
}

function slugify(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function isHeader(line: string): boolean {
  return /^\s*P\tE\tC\tT/.test(line);
}

function toFloat(value: string | undefined): number | undefined {
  if (value === undefined) return undefined;
  const n = Number.parseFloat(value.trim().replace(',', '.'));
  return Number.isFinite(n) ? n : undefined;
}

function main(): void {
  const content = readFileSync(join(ROOT, SOURCE_REL), 'utf8');
  const hash = createHash('sha256').update(content).digest('hex');
  const lines = content.split('\n').map((l) => l.replace(/\r$/, ''));

  const materials: Material[] = [];
  const seen = new Map<string, number>();
  let current: Material | null = null;
  let expectMaterial = false;

  for (const line of lines) {
    if (isHeader(line)) {
      expectMaterial = true;
      current = null;
      continue;
    }
    const cells = line.split('\t');
    const name = (cells[0] ?? '').trim();
    if (name.length === 0 || name === '```') continue;

    if (expectMaterial) {
      const p = toFloat(cells[1]);
      const e = toFloat(cells[2]);
      const c = toFloat(cells[3]);
      const t = toFloat(cells[4]);
      if (p !== undefined && e !== undefined && c !== undefined && t !== undefined) {
        let id = slugify(name);
        const count = seen.get(id) ?? 0;
        seen.set(id, count + 1);
        if (count > 0) id = `${id}-${count + 1}`;
        current = {
          id,
          name,
          armor: { p, e, c, t },
          pieces: [],
          source_refs: [{ path: SOURCE_REL, sha256: hash, ref: `entry:${id}` }]
        };
        materials.push(current);
      }
      expectMaterial = false;
      continue;
    }

    if (current) {
      const weight = toFloat(cells[1]);
      current.pieces.push(weight !== undefined ? { name, weight_kg: weight } : { name });
    }
  }

  const catalog = {
    version: 1,
    metadata: {
      source: SOURCE_REL,
      source_sha256: hash,
      imported_at: '2026-05-27',
      total_entries: materials.length,
      catalog_status: 'partial',
      notes:
        'Materiaux de protection du document paper : valeurs d armure P/E/C/T par materiau + pieces ' +
        '(par partie du corps) avec poids kg. Reconciliation avec protections.yaml (web) = E0.4b.'
    },
    materials
  };

  const yaml = `# Generated by \`pnpm catalogs:build:protections-paper\`. Do not edit by hand.\n${dump(
    catalog,
    { lineWidth: 120, noRefs: true }
  )}`;
  writeFileSync(join(ROOT, OUTPUT_REL), yaml, 'utf8');
  const pieceCount = materials.reduce((sum, m) => sum + m.pieces.length, 0);
  console.log(
    `protections-paper catalog written: ${materials.length} materiaux, ${pieceCount} pieces`
  );
}

main();
