import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import yaml from 'js-yaml';

const ROOT = join(import.meta.dirname ?? __dirname, '..');
const FICHES_DIR = join(ROOT, 'data/legacy/web-scraped/personnages/fiches');
const FICHES_RELATIVE = 'data/legacy/web-scraped/personnages/fiches';
const OUTPUT_PATH = join(ROOT, 'data/catalogs/legacy-characters.yaml');

interface LegacyCharacter {
  id: string;
  name: string;
  legacy_id: number;
  status: 'raw_reference_only' | 'covered' | 'partial';
  source_refs: Array<{ path: string; sha256: string; ref: string }>;
  metadata: { source: 'web-canonical'; web_only: true; auto_inventoried: true };
}

function extractName(content: string): string {
  const lines = content.split('\n');
  const contenuIdx = lines.findIndex((line) => line.trim() === '## Contenu');
  if (contenuIdx === -1) return 'Inconnu';
  for (let i = contenuIdx + 1; i < Math.min(contenuIdx + 10, lines.length); i += 1) {
    const candidate = lines[i].trim();
    if (candidate && !candidate.startsWith('#') && !candidate.startsWith('Source')) {
      return candidate;
    }
  }
  return 'Inconnu';
}

function build(): LegacyCharacter[] {
  const files = readdirSync(FICHES_DIR)
    .filter((file) => file.startsWith('character-') && file.endsWith('.md'))
    .sort((a, b) => {
      const numA = Number.parseInt(a.replace(/[^0-9]/g, ''), 10);
      const numB = Number.parseInt(b.replace(/[^0-9]/g, ''), 10);
      return numA - numB;
    });

  return files.map((file) => {
    const filePath = join(FICHES_DIR, file);
    const content = readFileSync(filePath, 'utf8');
    const sha256 = createHash('sha256').update(content).digest('hex');
    const legacyId = Number.parseInt(file.replace(/[^0-9]/g, ''), 10);
    const id = `legacy-character-${legacyId}`;
    const name = extractName(content);

    return {
      id,
      name,
      legacy_id: legacyId,
      status: 'raw_reference_only',
      source_refs: [{ path: `${FICHES_RELATIVE}/${file}`, sha256, ref: `entry:${id}` }],
      metadata: { source: 'web-canonical', web_only: true, auto_inventoried: true }
    };
  });
}

function main(): void {
  const characters = build();
  const today = new Date().toISOString().slice(0, 10);

  const payload = {
    version: 1,
    metadata: {
      source: FICHES_RELATIVE,
      imported_at: today,
      total_entries: characters.length,
      catalog_status: 'partial',
      notes:
        "Inventaire automatique des 96 fiches legacy web (raw_reference_only). Chaque fiche conserve son hash et son chemin source pour traçabilité ; aucune correction silencieuse des données. La promotion d'une fiche en 'covered' suppose une vérification manuelle des stats vs le catalogue canonique."
    },
    characters
  };

  const yamlOutput = yaml.dump(payload, {
    lineWidth: 120,
    noRefs: true,
    quotingType: '"',
    forceQuotes: false
  });
  const banner = '# Generated by `pnpm catalogs:build:legacy-characters`. Do not edit by hand.\n';
  writeFileSync(OUTPUT_PATH, banner + yamlOutput, 'utf8');

  execFileSync('pnpm', ['exec', 'prettier', '--write', OUTPUT_PATH], {
    cwd: ROOT,
    stdio: 'inherit'
  });
  console.log(`Wrote ${OUTPUT_PATH} (${characters.length} legacy characters)`);
}

main();
