import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import yaml from 'js-yaml';

const ROOT = join(import.meta.dirname ?? __dirname, '..');
const SOURCE_PATH = join(ROOT, 'data/legacy/web-scraped/documents/competences/index.md');
const OUTPUT_PATH = join(ROOT, 'data/catalogs/competences.yaml');

const FAMILIES = new Set([
  'Art',
  'Artisanat',
  'Combat',
  'Connaissance',
  'Jeu',
  'Maîtrise de soi',
  'Savoir-faire',
  'Sens',
  'Social',
  'Sport'
]);

interface SkillEntry {
  id: string;
  name: string;
  family: string;
  family_name: string;
  parent_id: string | null;
  source_refs: Array<{ path: string; sha256: string; ref: string }>;
  metadata: { source: string };
}

function slugify(value: string): string {
  return value
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function parse(): { skills: SkillEntry[]; sourceHash: string; relativeSourcePath: string } {
  const content = readFileSync(SOURCE_PATH, 'utf8');
  const sourceHash = createHash('sha256').update(content).digest('hex');
  const relativeSourcePath = 'data/legacy/web-scraped/documents/competences/index.md';
  const lines = content.split('\n');

  const startIdx = lines.findIndex((line) => line.trim() === 'Liste des compétences');
  if (startIdx === -1) {
    throw new Error('Source preamble "Liste des compétences" not found');
  }

  const skills: SkillEntry[] = [];
  let currentFamily: string | null = null;
  const idsSeen = new Map<string, number>();
  const knownSkillIds = new Set<string>();
  const knownByName: Array<{ id: string; name: string }> = [];

  for (let i = startIdx + 1; i < lines.length; i += 1) {
    const trimmed = lines[i].trim();
    if (!trimmed) continue;

    if (FAMILIES.has(trimmed)) {
      currentFamily = trimmed;
      continue;
    }

    if (!currentFamily) continue;

    const parenMatch = trimmed.match(/^(.+?)\s*\(([^)]+)\)\s*$/);
    const rawName = parenMatch ? parenMatch[1].trim() : trimmed;
    const parentText = parenMatch ? parenMatch[2].trim() : null;
    const baseId = slugify(rawName);

    let parentId: string | null = null;
    if (parentText) {
      const candidate = slugify(parentText);
      if (knownSkillIds.has(candidate)) {
        parentId = candidate;
      }
    }

    if (parentId === null) {
      const lower = rawName.toLowerCase();
      let best: { id: string; name: string } | null = null;
      for (const known of knownByName) {
        const prefix = `${known.name.toLowerCase()} `;
        if (lower.startsWith(prefix) && (!best || known.name.length > best.name.length)) {
          best = known;
        }
      }
      if (best) {
        parentId = best.id;
      }
    }

    const occurrence = idsSeen.get(baseId) ?? 0;
    idsSeen.set(baseId, occurrence + 1);
    let id: string;
    if (occurrence === 0) {
      id = baseId;
    } else if (parentId) {
      id = `${baseId}-${parentId}`;
    } else {
      id = `${baseId}-${slugify(currentFamily)}-${occurrence}`;
    }

    skills.push({
      id,
      name: rawName,
      family: slugify(currentFamily),
      family_name: currentFamily,
      parent_id: parentId,
      source_refs: [
        {
          path: relativeSourcePath,
          sha256: sourceHash,
          ref: `line:${i + 1}`
        }
      ],
      metadata: {
        source: 'web-canonical'
      }
    });
    knownSkillIds.add(id);
    knownByName.push({ id, name: rawName });
  }

  return { skills, sourceHash, relativeSourcePath };
}

function buildCatalog(): unknown {
  const { skills, sourceHash, relativeSourcePath } = parse();

  return {
    version: 1,
    metadata: {
      source: relativeSourcePath,
      source_sha256: sourceHash,
      imported_at: new Date().toISOString().slice(0, 10),
      total_entries: skills.length,
      total_families: 10,
      catalog_kind: 'open',
      catalog_status: 'partial',
      notes:
        'Compétences extraites de la liste web canonique. Hiérarchie parent_id explicite uniquement quand "(parent)" est notée dans la source. Spécialisations implicites à raffiner ensuite (R-5.3, R-5.7).'
    },
    skills: skills.map((skill) => ({
      id: skill.id,
      name: skill.name,
      family: skill.family,
      family_name: skill.family_name,
      parent_id: skill.parent_id,
      source_refs: skill.source_refs,
      metadata: skill.metadata
    }))
  };
}

function main(): void {
  const catalog = buildCatalog();
  const yamlOutput = yaml.dump(catalog, {
    lineWidth: 120,
    noRefs: true,
    quotingType: '"',
    forceQuotes: false
  });
  const banner = '# Generated by `pnpm catalogs:build:competences`. Do not edit by hand.\n';
  writeFileSync(OUTPUT_PATH, banner + yamlOutput, 'utf8');
  execFileSync('pnpm', ['exec', 'prettier', '--write', OUTPUT_PATH], {
    cwd: ROOT,
    stdio: 'inherit'
  });
  console.log(`Wrote ${OUTPUT_PATH}`);
}

main();
