/**
 * E0.3 — Lie chaque atout de `atouts.yaml` (web) à son entrée de définition prose dans
 * `lexique.yaml` (lexique paper), via `prose_refs`. Réconcilie web↔paper et signale les orphelins.
 *
 * - Match direct : slug(nom de l'atout) == id d'une entrée lexique (kind atout préféré).
 * - Sinon : `prose_orphan: true` (atout web sans définition prose paper).
 *
 * Idempotent. Chaîné après `build:atouts`. Voir docs/plan/PROSE-SOURCE-LINKAGE.md.
 *
 * Usage : `pnpm catalogs:link:atouts`
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { dump, load } from 'js-yaml';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ATOUTS_PATH = join(ROOT, 'data/catalogs/atouts.yaml');
const LEXIQUE_PATH = join(ROOT, 'data/catalogs/lexique.yaml');

interface ProseRef {
  catalog: 'lexique';
  entry_id: string;
  term: string;
}
interface Atout {
  id: string;
  name: string;
  prose_refs?: ProseRef[];
  prose_orphan?: boolean;
  [key: string]: unknown;
}
interface LexiqueEntry {
  id: string;
  term: string;
  kind: string;
}
interface AtoutsDoc {
  version: number;
  metadata: Record<string, unknown>;
  atouts?: Atout[];
  [key: string]: unknown;
}
interface LexiqueDoc {
  entries?: LexiqueEntry[];
  [key: string]: unknown;
}

function slugify(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function main(): void {
  const atoutsDoc = load(readFileSync(ATOUTS_PATH, 'utf8')) as AtoutsDoc;
  const lexiqueDoc = load(readFileSync(LEXIQUE_PATH, 'utf8')) as LexiqueDoc;
  const atouts = atoutsDoc.atouts ?? [];
  const lexique = lexiqueDoc.entries ?? [];

  // Index lexique by slug ; prefer an atout-kind entry when several share a slug.
  const bySlug = new Map<string, LexiqueEntry>();
  for (const entry of lexique) {
    const existing = bySlug.get(entry.id);
    if (!existing || (existing.kind !== 'atout' && entry.kind === 'atout')) {
      bySlug.set(entry.id, entry);
    }
  }

  const matchedLexiqueIds = new Set<string>();
  let direct = 0;
  let orphan = 0;

  for (const atout of atouts) {
    delete atout.prose_refs;
    delete atout.prose_orphan;

    const entry = bySlug.get(slugify(atout.name));
    if (entry) {
      atout.prose_refs = [{ catalog: 'lexique', entry_id: entry.id, term: entry.term }];
      matchedLexiqueIds.add(entry.id);
      direct += 1;
    } else {
      atout.prose_orphan = true;
      orphan += 1;
    }
  }

  const atoutEntries = lexique.filter((entry) => entry.kind === 'atout');
  const lexiqueOrphans = atoutEntries.filter((entry) => !matchedLexiqueIds.has(entry.id));

  const banner = '# Generated by `pnpm catalogs:build:atouts`. Do not edit by hand.\n';
  const yaml = dump(atoutsDoc, {
    lineWidth: 120,
    noRefs: true,
    quotingType: '"',
    forceQuotes: false
  });
  writeFileSync(ATOUTS_PATH, banner + yaml, 'utf8');
  execFileSync('pnpm', ['exec', 'prettier', '--write', 'data/catalogs/atouts.yaml'], {
    cwd: ROOT,
    stdio: 'ignore'
  });

  console.log(`link-atouts-lexique: ${atouts.length} atouts`);
  console.log(`  direct       : ${direct}`);
  console.log(`  prose_orphan : ${orphan}`);
  console.log(`  lexique atouts non lies (sur ${atoutEntries.length}) : ${lexiqueOrphans.length}`);
  if (lexiqueOrphans.length > 0) {
    console.log(
      `  ex. orphelins lexique: ${lexiqueOrphans
        .slice(0, 12)
        .map((e) => e.id)
        .join(', ')}`
    );
  }
}

main();
