/**
 * E2b — Attache les EffectModels AUTHORÉS (overlays `data/spell-effects/*.yaml`) aux sorts de
 * `spells.yaml` (champ `effect_model`).
 *
 * Chaque overlay est groupé par école (`school_id`) et porte, par id de sort, un EffectModel complet
 * PROPOSÉ et **à valider par le MJ** (`fidelity: pending` + `spec.requires_mj_validation: true`,
 * méthode Q-D8.2). Le tool :
 *   1. lit tous les overlays ;
 *   2. **valide** chaque EffectModel via `parseEffectModel` de rules-core (source d'autorité du schéma) ;
 *   3. vérifie que le sort existe et que son `school_id` correspond à l'overlay ;
 *   4. attache `effect_model` au sort (idempotent : purge d'abord les `effect_model` existants).
 *
 * Échoue bruyamment (exit 1) si un EffectModel est invalide ou cible un sort inconnu / d'une autre
 * école — le build canonique reste honnête. Chaîné après `link-spells-lexique` dans `build:magic`
 * (qui régénère spells.yaml depuis le grimoire ; cet ajout doit donc suivre).
 *
 * Usage : `pnpm catalogs:link:spell-effects`
 */
import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { dump, load } from 'js-yaml';

import { parseEffectModel } from '../packages/rules-core/src/effect-model.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SPELLS_PATH = join(ROOT, 'data/catalogs/spells.yaml');
const OVERLAY_DIR = join(ROOT, 'data/spell-effects');

interface Spell {
  id: string;
  name: string;
  school_id: string;
  effect_model?: unknown;
  [key: string]: unknown;
}
interface SpellsDoc {
  version: number;
  metadata: Record<string, unknown>;
  spells?: Spell[];
  [key: string]: unknown;
}
interface Overlay {
  version: number;
  school_id: string;
  effects: Record<string, unknown>;
}

function readOverlays(): Overlay[] {
  let files: string[];
  try {
    files = readdirSync(OVERLAY_DIR).filter((f) => f.endsWith('.yaml'));
  } catch {
    return [];
  }
  return files.sort().map((file) => load(readFileSync(join(OVERLAY_DIR, file), 'utf8')) as Overlay);
}

function main(): void {
  const spellsDoc = load(readFileSync(SPELLS_PATH, 'utf8')) as SpellsDoc;
  const spells = spellsDoc.spells ?? [];
  const byId = new Map<string, Spell>(spells.map((s) => [s.id, s]));

  // Idempotence : purge les effect_model existants avant de réattacher depuis les overlays.
  for (const spell of spells) delete spell.effect_model;

  const overlays = readOverlays();
  const errors: string[] = [];
  let attached = 0;
  const perSchool = new Map<string, number>();

  for (const overlay of overlays) {
    for (const [spellId, rawModel] of Object.entries(overlay.effects ?? {})) {
      const spell = byId.get(spellId);
      if (!spell) {
        errors.push(`overlay ${overlay.school_id}: sort inconnu "${spellId}"`);
        continue;
      }
      if (spell.school_id !== overlay.school_id) {
        errors.push(
          `sort "${spellId}" est de l'école "${spell.school_id}" mais déclaré dans l'overlay "${overlay.school_id}"`
        );
        continue;
      }
      try {
        // Valide contre le schéma EffectModel de rules-core (lève si invalide).
        parseEffectModel(rawModel);
      } catch (error) {
        errors.push(`EffectModel invalide pour "${spellId}": ${(error as Error).message}`);
        continue;
      }
      spell.effect_model = rawModel;
      attached += 1;
      perSchool.set(overlay.school_id, (perSchool.get(overlay.school_id) ?? 0) + 1);
    }
  }

  if (errors.length > 0) {
    console.error('link-spell-effects: ÉCHEC');
    for (const e of errors) console.error(`  - ${e}`);
    process.exit(1);
  }

  const banner = '# Generated by `pnpm catalogs:build:magic`. Do not edit by hand.\n';
  const yaml = dump(spellsDoc, {
    lineWidth: 100,
    noRefs: true,
    quotingType: '"',
    forceQuotes: false
  });
  writeFileSync(SPELLS_PATH, banner + yaml, 'utf8');
  execFileSync('pnpm', ['exec', 'prettier', '--write', 'data/catalogs/spells.yaml'], {
    cwd: ROOT,
    stdio: 'ignore'
  });

  console.log(`link-spell-effects: ${attached} effect_model attachés (fidelity: pending)`);
  for (const [school, n] of [...perSchool].sort()) console.log(`  ${school}: ${n}`);
  console.log('  (à valider par le MJ — requires_mj_validation: true)');
}

main();
