/**
 * E0.2 — Lie chaque sort de `spells.yaml` (grimoire web) à son entrée de définition prose dans
 * `lexique.yaml` (lexique paper), via `prose_refs`. Réconcilie web↔paper et signale les orphelins.
 *
 * - Match direct : slug(nom du sort) == id d'une entrée lexique.
 * - Variante (de masse / mineur / majeur / de distance) : lien vers l'entrée de **base** + `derived_from`.
 * - Sinon : `prose_orphan: true` (sort web sans définition prose paper).
 *
 * Idempotent (recalcule à chaque exécution). Chaîné après `build:magic`. Voir
 * docs/plan/PROSE-SOURCE-LINKAGE.md.
 *
 * Usage : `pnpm catalogs:link:lexique`
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { dump, load } from 'js-yaml';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SPELLS_PATH = join(ROOT, 'data/catalogs/spells.yaml');
const LEXIQUE_PATH = join(ROOT, 'data/catalogs/lexique.yaml');

interface ProseRef {
  catalog: 'lexique';
  entry_id: string;
  term: string;
}
interface Spell {
  id: string;
  name: string;
  prose_refs?: ProseRef[];
  derived_from?: string;
  prose_orphan?: boolean;
  [key: string]: unknown;
}
interface LexiqueEntry {
  id: string;
  term: string;
  kind: string;
}
interface Catalog<T> {
  version: number;
  metadata: Record<string, unknown>;
  [key: string]: unknown;
  spells?: T[];
  entries?: T[];
}

const VARIANT_SUFFIXES = [
  / de masse$/i,
  / de distance$/i,
  / majeure?$/i,
  / mineure?$/i,
  / de groupe$/i
];

function slugify(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function baseName(name: string): string | null {
  for (const suffix of VARIANT_SUFFIXES) {
    if (suffix.test(name)) return name.replace(suffix, '').trim();
  }
  return null;
}

function main(): void {
  const spellsDoc = load(readFileSync(SPELLS_PATH, 'utf8')) as Catalog<Spell>;
  const lexiqueDoc = load(readFileSync(LEXIQUE_PATH, 'utf8')) as Catalog<LexiqueEntry>;
  const spells = spellsDoc.spells ?? [];
  const lexique = lexiqueDoc.entries ?? [];

  // Index lexique by slug ; prefer a sort-kind entry when several share a slug.
  const bySlug = new Map<string, LexiqueEntry>();
  for (const entry of lexique) {
    const existing = bySlug.get(entry.id);
    if (!existing || (existing.kind !== 'sort' && entry.kind === 'sort'))
      bySlug.set(entry.id, entry);
  }

  const matchedLexiqueIds = new Set<string>();
  let direct = 0;
  let derived = 0;
  let orphan = 0;

  for (const spell of spells) {
    delete spell.prose_refs;
    delete spell.derived_from;
    delete spell.prose_orphan;

    const slug = slugify(spell.name);
    const directEntry = bySlug.get(slug);
    if (directEntry) {
      spell.prose_refs = [{ catalog: 'lexique', entry_id: directEntry.id, term: directEntry.term }];
      matchedLexiqueIds.add(directEntry.id);
      direct += 1;
      continue;
    }

    const base = baseName(spell.name);
    const baseEntry = base ? bySlug.get(slugify(base)) : undefined;
    if (baseEntry) {
      spell.prose_refs = [{ catalog: 'lexique', entry_id: baseEntry.id, term: baseEntry.term }];
      spell.derived_from = baseEntry.id;
      matchedLexiqueIds.add(baseEntry.id);
      derived += 1;
      continue;
    }

    spell.prose_orphan = true;
    orphan += 1;
  }

  const sortEntries = lexique.filter((entry) => entry.kind === 'sort');
  const lexiqueOrphans = sortEntries.filter((entry) => !matchedLexiqueIds.has(entry.id));

  const banner = '# Generated by `pnpm catalogs:build:magic`. Do not edit by hand.\n';
  const yaml = dump(spellsDoc, {
    lineWidth: 100,
    noRefs: true,
    quotingType: '"',
    forceQuotes: false
  });
  writeFileSync(SPELLS_PATH, banner + yaml, 'utf8');
  execFileSync('pnpm', ['exec', 'prettier', '--write', 'data/catalogs/spells.yaml'], {
    cwd: ROOT,
    stdio: 'ignore'
  });

  console.log(`link-spells-lexique: ${spells.length} sorts`);
  console.log(`  direct        : ${direct}`);
  console.log(`  derived (var) : ${derived}`);
  console.log(`  prose_orphan  : ${orphan}`);
  console.log(`  lexique sorts non lies (sur ${sortEntries.length}) : ${lexiqueOrphans.length}`);
  if (lexiqueOrphans.length > 0) {
    console.log(
      `  ex. orphelins lexique: ${lexiqueOrphans
        .slice(0, 12)
        .map((e) => e.id)
        .join(', ')}`
    );
  }
}

main();
