/**
 * E0.3 / E0.3b — Lie chaque atout de `atouts.yaml` (web) au lexique paper (`lexique.yaml`).
 *
 *  1. Match direct : slug(nom) == id d'une entrée lexique (atout préféré) → `prose_refs`.
 *  2. Sinon — GÉNÉRATION ANCRÉE (E0.3b) : `generated_prose` = expansion lisible de la ligne `effect`
 *     du catalogue + cadre d'activation (jamais d'invention libre), marquée `prose_origin: templated`,
 *     `validation: pending`, `low_confidence` si l'effet source est absent. Promue par arbitrage MJ
 *     (Q-D8.2). Distincte de `prose_refs` (paper autoritaire). Voir docs/plan/PROSE-SOURCE-LINKAGE.md.
 *
 * Idempotent. Chaîné après `build:atouts`.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { dump, load } from 'js-yaml';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ATOUTS_PATH = join(ROOT, 'data/catalogs/atouts.yaml');
const LEXIQUE_PATH = join(ROOT, 'data/catalogs/lexique.yaml');

interface ProseRef {
  catalog: 'lexique';
  entry_id: string;
  term: string;
}
interface Atout {
  id: string;
  name: string;
  effect?: string;
  activation?: string;
  prose_refs?: ProseRef[];
  prose_orphan?: boolean;
  generated_prose?: string;
  prose_origin?: 'templated';
  validation?: 'pending';
  low_confidence?: boolean;
  [key: string]: unknown;
}
interface LexiqueEntry {
  id: string;
  term: string;
  kind: string;
}
interface AtoutsDoc {
  version: number;
  metadata: Record<string, unknown>;
  atouts?: Atout[];
  [key: string]: unknown;
}
interface LexiqueDoc {
  entries?: LexiqueEntry[];
  [key: string]: unknown;
}

function slugify(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

/** Readable prose anchored on the canonical effect line + activation frame. No free invention. */
function generateProse(atout: Atout): { prose: string; lowConfidence: boolean } {
  const effect = (atout.effect ?? '')
    .trim()
    .replace(/\s*\/\s*R\b/g, ' par réussite')
    .replace(/\s*\/\s*Niv\.?/gi, ' par niveau du personnage')
    .replace(/\s+/g, ' ')
    .trim();
  const frame =
    atout.activation === 'ephemere' || atout.activation === 'éphémère'
      ? 'Atout éphémère'
      : atout.activation === 'permanent'
        ? 'Atout permanent'
        : 'Atout';
  if (effect.length === 0) {
    return { prose: `${frame} : effet non détaillé dans le catalogue.`, lowConfidence: true };
  }
  return { prose: `${frame} : ${effect.replace(/\.*$/, '')}.`, lowConfidence: false };
}

function clear(atout: Atout): void {
  delete atout.prose_refs;
  delete atout.prose_orphan;
  delete atout.generated_prose;
  delete atout.prose_origin;
  delete atout.validation;
  delete atout.low_confidence;
}

function main(): void {
  const atoutsDoc = load(readFileSync(ATOUTS_PATH, 'utf8')) as AtoutsDoc;
  const lexiqueDoc = load(readFileSync(LEXIQUE_PATH, 'utf8')) as LexiqueDoc;
  const atouts = atoutsDoc.atouts ?? [];
  const lexique = lexiqueDoc.entries ?? [];

  const bySlug = new Map<string, LexiqueEntry>();
  for (const entry of lexique) {
    const existing = bySlug.get(entry.id);
    if (!existing || (existing.kind !== 'atout' && entry.kind === 'atout')) {
      bySlug.set(entry.id, entry);
    }
  }

  const matchedLexiqueIds = new Set<string>();
  let direct = 0;
  let generated = 0;
  let lowConf = 0;

  for (const atout of atouts) {
    clear(atout);
    const entry = bySlug.get(slugify(atout.name));
    if (entry) {
      atout.prose_refs = [{ catalog: 'lexique', entry_id: entry.id, term: entry.term }];
      matchedLexiqueIds.add(entry.id);
      direct += 1;
      continue;
    }
    const { prose, lowConfidence } = generateProse(atout);
    atout.generated_prose = prose;
    atout.prose_origin = 'templated';
    atout.validation = 'pending';
    if (lowConfidence) {
      atout.low_confidence = true;
      lowConf += 1;
    }
    generated += 1;
  }

  const atoutEntries = lexique.filter((entry) => entry.kind === 'atout');
  const lexiqueOrphans = atoutEntries.filter((entry) => !matchedLexiqueIds.has(entry.id));

  const banner = '# Generated by `pnpm catalogs:build:atouts`. Do not edit by hand.\n';
  const yaml = dump(atoutsDoc, {
    lineWidth: 120,
    noRefs: true,
    quotingType: '"',
    forceQuotes: false
  });
  writeFileSync(ATOUTS_PATH, banner + yaml, 'utf8');
  execFileSync('pnpm', ['exec', 'prettier', '--write', 'data/catalogs/atouts.yaml'], {
    cwd: ROOT,
    stdio: 'ignore'
  });

  console.log(`link-atouts-lexique: ${atouts.length} atouts`);
  console.log(`  prose_refs paper : ${direct}`);
  console.log(
    `  generated_prose  : ${generated} (dont low_confidence: ${lowConf}) -> validation pending`
  );
  console.log(`  prose_orphan     : 0 (chaque atout a une definition)`);
  console.log(`  lexique atouts non lies (sur ${atoutEntries.length}) : ${lexiqueOrphans.length}`);
}

main();
